services:
  autoretrieve:
    build: .
    environment:
      FULLNODE_API_INFO: ${FULLNODE_API_INFO:-wss://api.chain.love}
      AUTORETRIEVE_DATA_DIR: $AUTORETRIEVE_DATA_DIR
      AUTORETRIEVE_ENDPOINT_URL: $AUTORETRIEVE_ENDPOINT_URL
      AUTORETRIEVE_ENDPOINT_TYPE: $AUTORETRIEVE_ENDPOINT_TYPE
      AUTORETRIEVE_USE_FULLRT: $AUTORETRIEVE_USE_FULLRT
      AUTORETRIEVE_LOG_RESOURCE_MANAGER: $AUTORETRIEVE_LOG_RESOURCE_MANAGER
      AUTORETRIEVE_LOG_RETRIEVALS: $AUTORETRIEVE_LOG_RETRIEVALS
    ports: 
      - "6746:6746"
    volumes:
      - ${AUTORETRIEVE_DATA_DIR:-~/.autoretrieve}:/app/data
  # db:
  #   image: postgres